### ISSUE TITLE
sam deploy fails with Exit status 255 due to missing S3 permissions

### ISSUE THREAD

**Issue by Huniku** [aws-samples/aws-sdk-js-v3-workshop#13]
**Describe the bug**
The deploy step of yarn bpd fails with exit status 255

**To Reproduce**
`yarn mb`
`yarn bpd`

**Expected behavior**
yarn bpd passes

**Stack Trace**
```
11 silly lifecycle aws-sdk-js-v3-workshop-backend@1.0.0~deploy: Args: [ '-c',
11 silly lifecycle   'sam deploy --template-file packaged.yaml --stack-name $AWS_JS_SDK_ID --capabilities CAPABILITY_IAM' ]
12 silly lifecycle aws-sdk-js-v3-workshop-backend@1.0.0~deploy: Returned: code: 255  signal: null
13 info lifecycle aws-sdk-js-v3-workshop-backend@1.0.0~deploy: Failed to exec deploy script
14 verbose stack Error: aws-sdk-js-v3-workshop-backend@1.0.0 deploy: `sam deploy --template-file packaged.yaml --stack-name $AWS_JS_SDK_ID --capabilities CAPABILITY_IAM`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/Users/<redacted>/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/Users/<redacted>/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Additional context**
Updating default region to `us-west-2` as indicated by #12 does not resolve the issue

**Comment by trivikr** [comment]
Is this issue on Windows?

**Comment by Huniku** [comment]
I'm seeing it on macOS

**Comment by Huniku** [comment]
Looks like the corresponding error in CloudFormation is:
```
Your access has been denied by S3, please make sure your request credentials have permission to GetObject for whiteben-aws-js-sdk-v3-workshop-5/<redacted>. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: <redacted>)
```
On the GetNote lambda

**Comment by Huniku** [comment]
Full deploy trace:

```
> sam deploy --template-file packaged.yaml --stack-name $AWS_JS_SDK_ID --capabilities 

CAPABILITY_IAM --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
deploy command is called

Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name <redacted>-aws-js-sdk-v3-workshop-5
Exception: Command '['aws', 'cloudformation', 'deploy', '--capabilities', 'CAPABILITY_IAM', '--stack-name', '<redacted>-aws-js-sdk-v3-workshop-5', '--template-file', 'packaged.yaml']' returned non-zero exit status 255.
```

Full yaml:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AwsJsSdkV3Workshop

  Backend for the AWS JS SDK v3 workshop

  '
Globals:
  Api:
    Cors: '''*'''
  Function:
    Runtime: nodejs10.x
    Timeout: 180
    Environment:
      Variables:
        tableName:
          Ref: NotesTable
Resources:
  NotesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: aws-js-sdk-workshop-notes
      PrimaryKey:
        Name: noteId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  CreateNote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://<redacted>-aws-js-sdk-v3-workshop-5/<redacted>
      Handler: app.main
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: NotesTable
      Events:
        CreateNote:
          Type: Api
          Properties:
            Path: /notes
            Method: post
  GetNote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://<redacted>-aws-js-sdk-v3-workshop-5/<redacted>
      Handler: app.main
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: NotesTable
      Events:
        GetNote:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: get
  ListNotes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://<redacted>-aws-js-sdk-v3-workshop-5/<redacted>
      Handler: app.main
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: NotesTable
      Events:
        ListNotes:
          Type: Api
          Properties:
            Path: /notes
            Method: get
  UpdateNote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://<redacted>-aws-js-sdk-v3-workshop-5/<redacted>
      Handler: app.main
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: NotesTable
      Events:
        UpdateNote:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: put
  DeleteNote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://<redacted>-aws-js-sdk-v3-workshop-5/<redacted>
      Handler: app.main
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: NotesTable
      Events:
        DeleteNote:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: delete
Outputs:
  NotesApi:
    Description: API Gateway endpoint URL for Notes API
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/
```

**Comment by Kyle-Helmick** [comment]
Cognito isn't deployed in us-west-2. I'd suggest writing the cloudformation templates to force us-east-1 (somewhere where Cognito is deployed)

**Comment by Huniku** [comment]
I'll try that, but the script is hardcoded to use `us-west-2` (see #12)

**Comment by trivikr** [comment]
Tagged this issue to explore CDK for setting up infrastructure

**Comment by trivikr** [comment]
This issue non longer exists, as we don't use SAM CLI anymore
Refs: https://github.com/aws-samples/aws-sdk-js-v3-workshop/pull/179
